[package]
name = "magentadb-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
magentadb-crypto = { path = "../magentadb-crypto" }
dashmap = "6.1.0"

