[package]
name = "magentadb-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
chacha20poly1305 = "0.11.0-rc.0"
rand = "0.8"
hmac = "0.12"
sha2 = "0.10"
base64 = "0.21"
hex = "0.4"
anyhow = "1.0"